//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avto_Salons
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInformation
    {
        public string EmployeeSurname { get; set; }
        public string EmployeePosition { get; set; }
        public string EmployeeEmail { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
        public int CarYear { get; set; }
        public decimal CarPrice { get; set; }
        public string ConfigurationName { get; set; }
        public decimal ConfigurationPrice { get; set; }
        public string PaymentMethod { get; set; }
        public string CustomerSurname { get; set; }
    }
}
