//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avto_Salons
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SALON_AVTOEntities : DbContext
    {
        public SALON_AVTOEntities()
            : base("name=SALON_AVTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrandModels> BrandModels { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Configurations> Configurations { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Payment_Method> Payment_Method { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ServiceOrderCars> ServiceOrderCars { get; set; }
        public virtual DbSet<ServiceOrders> ServiceOrders { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierCars> SupplierCars { get; set; }
        public virtual DbSet<TestDrives> TestDrives { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ClientInformation> ClientInformation { get; set; }
    }
}
