//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avto_Salons
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderCars
    {
        public int Id_ServiceOrderCars { get; set; }
        public int service_order_Id { get; set; }
        public int car_Id { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual ServiceOrders ServiceOrders { get; set; }
    }
}
